const IMAGES = {
  Image1: new URL("./Image1.jpg", import.meta.url).href,
  Image2: new URL("./Image2.jpg", import.meta.url).href,
  Image3: new URL("./Image3.jpg", import.meta.url).href,
  Image4: new URL("./Image4.jpg", import.meta.url).href,
  Image5: new URL("./Image5.jpg", import.meta.url).href,
  Image6: new URL("./Image6.jpg", import.meta.url).href,
  Image7: new URL("./Image7.jpg", import.meta.url).href,
  Image8: new URL("./Image8.jpg", import.meta.url).href,
  Image9: new URL("./Image9.jpg", import.meta.url).href,
  Image10: new URL("./Image10.jpg", import.meta.url).href,
  Image11: new URL("./Image11.jpg", import.meta.url).href,
  Image12: new URL("./Image12.jpg", import.meta.url).href,
  Image13: new URL("./Image13.jpg", import.meta.url).href,
  Image14: new URL("./Image14.jpg", import.meta.url).href,
  Image15: new URL("./Image15.jpg", import.meta.url).href,
  Image16: new URL("./Image16.jpg", import.meta.url).href,
  Image17: new URL("./Image17.jpg", import.meta.url).href,
  Image18: new URL("./Image18.jpg", import.meta.url).href,
  Image19: new URL("./Image19.jpg", import.meta.url).href,
  Image20: new URL("./Image20.jpg", import.meta.url).href,
  Image21: new URL("./Image21.jpg", import.meta.url).href,
  Image22: new URL("./Image22.jpg", import.meta.url).href,
  Image23: new URL("./Image23.jpg", import.meta.url).href,
  Image24: new URL("./Image24.png", import.meta.url).href,
  Image25: new URL("./Image25.png", import.meta.url).href,
};

export default IMAGES;
